POST http://localhost:5000/schedule/createschedule
Content-Type: application/json

{
  "courseId":"66ea96311f254f8d8b4bc443",
  "startDate":"2024-09-20",
  "endDate":"2025-03-20",
  "dayOfWeek":[1,3,5],
  "time":"12:00:00"
}

###
GET http://localhost:5000/schedule/getschedules

###
GET http://localhost:5000/schedule/getschedule/66ebcd1db9250edc7f1b81b0

###
GET http://localhost:5000/schedule/getscheduleofacourse/66ebccbcb9250edc7f1b81aa

