POST http://localhost:5000/user/login
Content-Type: application/json

{
  "email":"superadmin@example.com",
  "password":"superadminpassword1234"
}

###
POST http://localhost:5000/user/signup
Content-Type: application/json

{
  "username":"admin2",
  "email":"admin2@example.com",
  "password":"admin234"
}

###
GET http://localhost:5000/user/getuserinpending
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiU3VwZXJBZG1pbiIsImlhdCI6MTcyNzY0MTY5NSwiZXhwIjoxNzI3NjQzNDk1fQ.gPVfzKYEo5XLMpiZEkbZj62iIURG1qzmFvGqUv1i1IA

###
PATCH http://localhost:5000/user/assignrole/66f1a4e2ed22f35d3a2b600e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiU3VwZXJBZG1pbiIsImlhdCI6MTcyNzY0MTY5NSwiZXhwIjoxNzI3NjQzNDk1fQ.gPVfzKYEo5XLMpiZEkbZj62iIURG1qzmFvGqUv1i1IA
Content-Type: application/json

{
  "role":"Admin"
}

###
GET http://localhost:5000/user/getadmins
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiU3VwZXJBZG1pbiIsImlhdCI6MTcyNzc5NDczNCwiZXhwIjoxNzI3Nzk2NTM0fQ.JNzREr-ZD1-Cy7up-FOptKWlG8v_Tr4HEB2BapGl4M4

###
GET http://localhost:5000/user/getregistrars
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiU3VwZXJBZG1pbiIsImlhdCI6MTcyNzY0MTY5NSwiZXhwIjoxNzI3NjQzNDk1fQ.gPVfzKYEo5XLMpiZEkbZj62iIURG1qzmFvGqUv1i1IA