POST http://localhost:5000/course/createcourse
Content-Type: application/json

{
  "courseName":"Graphics Design1",
  "duration":"2 month",
  "description":"GD description",
  "price": 3000,
  "courseRegistrationStatus": "OnProgress",
  "schedule": {
     "startDate":"2024-09-20",
     "endDate":"2024-11-20",
     "dayOfWeek":[2,4,6],
     "time":"12:00:00"
  }
}

###

GET http://localhost:5000/course/getcourses

###

GET http://localhost:5000/course/getspecificcourse/66ebccbcb9250edc7f1b81aa

###
PATCH http://localhost:5000/course/editcourse/66eaa3212a2a98b8f5aa30c3
Content-Type: application/json

{
  "courseName":"GD",
  "duration":"6 months",
  "description":"this is updated description of GD",
  "price":6000
}
###
DELETE http://localhost:5000/course/deletecourse/66ebcd1db9250edc7f1b81af