POST http://localhost:5000/course/createcourse
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiU3VwZXJBZG1pbiIsImlhdCI6MTcyNzU1MzI1NywiZXhwIjoxNzI3NTU1MDU3fQ.ksvVyCPF51113AjGsK4pSJwYXDuWTyifNPoVjxIW33A
Content-Type: application/json

{
  "courseName":"MERN Stack Online",
  "duration":"6 month",
  "description":"Dive deep into the world of full-stack web development with our MERN Stack In-Person Course. Join us at our campus for face-to-face training on MongoDB, Express.js, React.js, and Node.js. This course is tailored for individuals who prefer hands-on, collaborative learning environments. With in-class coding sessions, real-world projects, and personalized guidance from experienced developers, you'll build the skills to create powerful web applications. Perfect for both beginners and professionals seeking to refine their skills in a structured classroom setting",
  "price": 6000,
  "courseRegistrationStatus": "OnRegistration",
  "learningMode":"InPerson",
  "spotLimit":50,
  "schedule": {
     "startDate":"2024-09-20",
     "endDate":"2025-11-20",
     "dayOfWeek":[1,3,5],
     "time":"12:00:00"
  }
}


###

GET http://localhost:5000/course/getcourses

###

GET http://localhost:5000/course/getspecificcourse/66f86016808802a6614fde65

###
PATCH http://localhost:5000/course/editcourse/66eaa3212a2a98b8f5aa30c3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiU3VwZXJBZG1pbiIsImlhdCI6MTcyNzE2MjIwOSwiZXhwIjoxNzI3MTY0MDA5fQ.HalHgVOtzzRMtDCezZOLUIvZuOFUWhzV7X8sPj6ZTNs
Content-Type: application/json

{
  "courseName":"GD",
  "duration":"6 months",
  "description":"this is updated description of GD",
  "price":6000
}
###
DELETE http://localhost:5000/course/deletecoursecollection